swagger: "2.0"
info:
  title: "Trader Joe API"
schemes:
  - "http"
paths:
  /v2/pool/liquidity/{lpToken}:
    $ref: "pools.yaml#/liquidity"
  /v2/pool/volume/{lpToken}:
    $ref: "pools.yaml#/volume"
  /v2/pool/fees/{lpToken}:
    $ref: "pools.yaml#/fees"
  /v2/pool/APR/{lpToken}:
    $ref: "pools.yaml#/APR"
  /v2/farm/list:
    $ref: "farm.yaml#/list"
  /v2/farm/poolweight/{lpToken}:
    $ref: "farm.yaml#/poolweight"
  /v2/farm/liquidity/{lpToken}:
    $ref: "farm.yaml#/liquidity"
  /v2/farm/APR/{lpToken}:
    $ref: "farm.yaml#/APR"
  /v2/farm/bonusAPR/{lpToken}:
    $ref: "farm.yaml#/bonusAPR"
  /v1/lending/list:
    $ref: "bank.yaml#/list"
  /v1/lending/supply:
    $ref: "bank.yaml#/supply"
  /v1/lending/borrow:
    $ref: "bank.yaml#/borrow"
  /v2/lending/depositAPY/{lendingPool}:
    $ref: "bank.yaml#/depositAPY"
  /v2/lending/depositRewardsAPR/{lendingPool}:
    $ref: "bank.yaml#/depositRewardsAPR"
  /v2/lending/borrowAPY/{lendingPool}:
    $ref: "bank.yaml#/borrowAPY"
  /v2/lending/borrowRewardsAPR/{lendingPool}:
    $ref: "bank.yaml#/borrowRewardsAPR"
  /v2/stake/fees:
    $ref: "stake.yaml#/fees"
  /v2/stake/APR:
    $ref: "stake.yaml#/APR"
  /v2/stake/APY:
    $ref: "stake.yaml#/APY"
  /v1/nft/hat/{id}:
    $ref: "nft.yaml#/hat"
  /v1/priceavax/{tokenAddress}:
    $ref: "token.yaml#/priceavax"
  /v1/priceusd/{tokenAddress}:
    $ref: "token.yaml#/priceusd"
  /v1/supply/circulating:
    $ref: "supply.yaml#/circulating"
  /v1/supply/circulating-adjusted:
    $ref: "supply.yaml#/circulating-adjusted"
  /v1/supply/total:
    $ref: "supply.yaml#/total"
  /v1/supply/max:
    $ref: "supply.yaml#/max"